# Generated by Django 4.2.1 on 2023-08-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal_money',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
