# Generated by Django 4.2.1 on 2023-06-11 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_joined_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="joined_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 6, 11, 8, 39, 43, 764448, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
