# Generated by Django 4.2.1 on 2023-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_joined_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("worker", "Worker"),
                    ("client", "Client"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
