# Generated by Django 4.2.1 on 2023-06-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.discounttype",
            ),
        ),
    ]
