# Generated by Django 4.2.1 on 2023-06-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_referral"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="money", field=models.IntegerField(default=0),
        ),
    ]
