# Generated by Django 4.2.1 on 2023-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="services_count",
            field=models.IntegerField(default=0),
        ),
    ]
