# Generated by Django 4.2.1 on 2023-06-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_user_services_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="email",),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, default="user", max_length=100, null=True, unique=True
            ),
        ),
    ]
