# Generated by Django 4.2.1 on 2023-07-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_remove_user_phone_number_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user", name="profit", field=models.IntegerField(default=0),
        ),
    ]
