# Generated by Django 4.2.1 on 2023-07-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_user_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="product_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
