# Generated by Django 4.2.1 on 2023-07-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_user_product_count"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="product_count",),
    ]
