# Generated by Django 4.2.1 on 2023-07-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_remove_user_product_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="product_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
