# Generated by Django 4.2.1 on 2023-07-13 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cashbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=54)),
                ("balance", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CashboxCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=124)),
            ],
        ),
        migrations.CreateModel(
            name="CashboxOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.IntegerField()),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Consumables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("count", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                ("cost_price", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EmployerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("service_count", models.IntegerField(default=0)),
                ("product_count", models.IntegerField(default=0)),
                ("salary", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ModelChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("change_type", models.CharField(max_length=50)),
                ("old_value", models.CharField(blank=True, max_length=100)),
                ("new_value", models.CharField(blank=True, max_length=100)),
                (
                    "change_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("acceptance", "Приемка"),
                            ("database_loading", "Загрузка в базу"),
                            ("unpacking", "Распаковка"),
                            ("quality_check", "Выдача ОТК"),
                            ("invoice_generation", "Выставка счета"),
                            ("dispatch", "Отправка"),
                            ("dispatched", "Оправленно"),
                        ],
                        default="database_loading",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("amount", models.IntegerField(default=0)),
                ("cost_price", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "day",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(31),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(12),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MaxValueValidator(2070),
                            django.core.validators.MinValueValidator(2020),
                        ],
                    ),
                ),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                ("defective", models.IntegerField(blank=True, default=0)),
                ("good_quality", models.IntegerField(blank=True, default=0)),
                ("discount", models.IntegerField(default=0)),
                (
                    "cashbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm_app.cashbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("before_defective", models.BooleanField(default=False)),
                ("discount", models.BooleanField(default=True)),
                ("price", models.IntegerField()),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("single", models.BooleanField(default=False)),
                ("acceptance", models.BooleanField(default=False)),
            ],
            options={"ordering": ["type"],},
        ),
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("cost_price", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm_app.order"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="services_in_order",
                        to="crm_app.service",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="service",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="services",
                to="crm_app.servicetype",
            ),
        ),
        migrations.CreateModel(
            name="OrderService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("count", models.IntegerField(default=0)),
                ("salary", models.IntegerField(default=0)),
                ("confirmed", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_service",
                        to="crm_app.order",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="order_service",
                        to="crm_app.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderConsumables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("cost_price", models.IntegerField(default=0)),
                ("price", models.IntegerField(default=0)),
                (
                    "consumable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm_app.consumables",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm_app.order"
                    ),
                ),
            ],
        ),
    ]
