# Generated by Django 4.2.1 on 2023-06-11 08:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("profit", models.IntegerField(default=0)),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm_app.client",
                    ),
                ),
            ],
            options={"abstract": False,},
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("salary", models.IntegerField(default=0)),
            ],
            options={"abstract": False,},
            bases=("users.user",),
        ),
        migrations.CreateModel(
            name="ModelChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("Created", "Created"),
                            ("Updated", "Updated"),
                            ("Deleted", "Deleted"),
                        ],
                        max_length=10,
                    ),
                ),
                ("change_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("1", "Accepted"),
                            ("2", "Waiting for payment"),
                            ("3", "Sent to cargo"),
                            ("4", "Self export"),
                            ("5", "Canceled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                ("cost_price", models.IntegerField(default=0)),
                ("count", models.IntegerField(default=0)),
                ("date", models.DateField()),
                (
                    "day",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(31),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "month",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(12),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        default=2023,
                        validators=[
                            django.core.validators.MaxValueValidator(2070),
                            django.core.validators.MinValueValidator(2020),
                        ],
                    ),
                ),
                ("time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=124)),
                ("price", models.IntegerField()),
                ("cost_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Сashbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=54)),
                ("balance", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=54)),
                ("count", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="crm_app.order"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="cashbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm_app.сashbox"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm_app.client"
            ),
        ),
        migrations.CreateModel(
            name="EmployerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("count", models.IntegerField(default=0)),
                ("salary", models.IntegerField(default=0)),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm_app.employer",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm_app.order"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="crm_app.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="cashboxusers",
            name="cashbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="crm_app.сashbox"
            ),
        ),
        migrations.AddField(
            model_name="cashboxusers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cashboxoperaion",
            name="cashbox_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashbox_from",
                to="crm_app.сashbox",
            ),
        ),
        migrations.AddField(
            model_name="cashboxoperaion",
            name="cashbox_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashbox_to",
                to="crm_app.сashbox",
            ),
        ),
        migrations.AddField(
            model_name="cashboxoperaion",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="crm_app.cashboxcategory",
            ),
        ),
    ]
