# Generated by Django 4.2.1 on 2023-06-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="ContactInfo",),
    ]
