# Generated by Django 4.2.1 on 2023-07-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employerorder", old_name="count", new_name="product_count",
        ),
        migrations.AddField(
            model_name="employerorder",
            name="service_count",
            field=models.IntegerField(default=0),
        ),
    ]
