# Generated by Django 4.2.1 on 2023-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_order_actual_shipment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='referral_money',
            field=models.IntegerField(default=0),
        ),
    ]
