# Generated by Django 4.2.1 on 2023-06-11 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm_app", "0003_delete_contactinfo"),
    ]

    operations = [
        migrations.RemoveField(model_name="employer", name="user_ptr",),
        migrations.AlterField(
            model_name="employerservice",
            name="employer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="Client",),
        migrations.DeleteModel(name="Employer",),
    ]
