# Generated by Django 4.2.1 on 2023-06-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0004_remove_employer_user_ptr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stage",
            field=models.CharField(
                choices=[
                    ("accepted", "Accepted"),
                    ("waiting", "Waiting"),
                    ("sent to cargo", "Sent to Cargo"),
                    ("self export", "Self Export"),
                    ("canceled", "Canceled"),
                ],
                default="accepted",
                max_length=20,
            ),
        ),
    ]
