# Generated by Django 4.2.1 on 2023-06-13 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm_app", "0005_alter_order_stage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CashboxOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money", models.IntegerField()),
                ("comment", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(model_name="cashboxusers", name="cashbox",),
        migrations.RemoveField(model_name="cashboxusers", name="user",),
        migrations.RenameModel(old_name="Сashbox", new_name="Cashbox",),
        migrations.DeleteModel(name="CashboxOperaion",),
        migrations.DeleteModel(name="CashboxUsers",),
        migrations.AddField(
            model_name="cashboxoperation",
            name="cashbox_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashbox_from",
                to="crm_app.cashbox",
            ),
        ),
        migrations.AddField(
            model_name="cashboxoperation",
            name="cashbox_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cashbox_to",
                to="crm_app.cashbox",
            ),
        ),
        migrations.AddField(
            model_name="cashboxoperation",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="crm_app.cashboxcategory",
            ),
        ),
        migrations.AddField(
            model_name="cashboxoperation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
