# Generated by Django 4.2.1 on 2023-06-13 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0006_cashboxoperation_remove_cashboxusers_cashbox_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashboxoperation",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cashboxoperation",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
