# Generated by Django 4.2.1 on 2023-06-15 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0007_cashboxoperation_date_cashboxoperation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="defective",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="employerservice",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="modelchangelog",
            name="change_timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
