# Generated by Django 4.2.1 on 2023-06-15 06:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0008_order_defective_alter_employerservice_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cashbox",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm_app.cashbox",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="stage",
            field=models.CharField(
                choices=[
                    ("accepted", "Принято"),
                    ("acceptance", "Приемка"),
                    ("database_loading", "Загрузка в базу"),
                    ("unpacking", "Распаковка"),
                    ("quality_check", "Выдача ОТК"),
                    ("invoice_generation", "Выставка счета"),
                    ("dispatch", "Отправка"),
                ],
                default="accepted",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
