# Generated by Django 4.2.1 on 2023-06-15 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm_app", "0009_alter_order_cashbox_alter_order_stage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelchangelog",
            name="new_value",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="modelchangelog",
            name="old_value",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="modelchangelog",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Product",),
    ]
