# Generated by Django 4.2.1 on 2023-06-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0010_modelchangelog_new_value_modelchangelog_old_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
