# Generated by Django 4.2.1 on 2023-06-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0011_order_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cashbox",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="crm_app.cashbox",
            ),
        ),
    ]
