# Generated by Django 4.2.1 on 2023-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0012_alter_order_cashbox"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stage",
            field=models.CharField(
                choices=[
                    ("acceptance", "Приемка"),
                    ("database_loading", "Загрузка в базу"),
                    ("unpacking", "Распаковка"),
                    ("quality_check", "Выдача ОТК"),
                    ("invoice_generation", "Выставка счета"),
                    ("dispatch", "Отправка"),
                ],
                default="acceptance",
                max_length=20,
            ),
        ),
    ]
