# Generated by Django 4.2.1 on 2023-06-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0013_alter_order_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="before_defective",
            field=models.BooleanField(default=False),
        ),
    ]
