# Generated by Django 4.2.1 on 2023-06-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0015_orderservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="good_quality",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
