# Generated by Django 4.2.1 on 2023-06-28 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0020_servicetype_serviceorder_service_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="service", name="type",),
    ]
