# Generated by Django 4.2.1 on 2023-06-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0021_remove_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="crm_app.servicetype",
            ),
        ),
    ]
