# Generated by Django 4.2.1 on 2023-06-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0022_service_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceorder",
            name="amount",
            field=models.IntegerField(default=0),
        ),
    ]
