# Generated by Django 4.2.1 on 2023-06-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0023_serviceorder_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="services",
                to="crm_app.servicetype",
            ),
        ),
        migrations.AlterField(
            model_name="serviceorder",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="services_in_order",
                to="crm_app.service",
            ),
        ),
    ]
