# Generated by Django 4.2.1 on 2023-07-01 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm_app", "0024_alter_service_type_alter_serviceorder_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="stage",
            field=models.CharField(
                choices=[
                    ("acceptance", "Приемка"),
                    ("database_loading", "Загрузка в базу"),
                    ("unpacking", "Распаковка"),
                    ("quality_check", "Выдача ОТК"),
                    ("invoice_generation", "Выставка счета"),
                    ("dispatch", "Отправка"),
                ],
                default="database_loading",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmployerOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("salary", models.IntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employer_orders",
                        to="crm_app.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="employer_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
