# Generated by Django 4.2.1 on 2023-07-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0025_alter_order_stage_employerorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerorder",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
