# Generated by Django 4.2.1 on 2023-07-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0026_employerorder_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelchangelog",
            name="change_type",
            field=models.CharField(max_length=10),
        ),
    ]
