# Generated by Django 4.2.1 on 2023-07-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0027_alter_modelchangelog_change_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service", name="cost_price", field=models.FloatField(),
        ),
    ]
