# Generated by Django 4.2.1 on 2023-07-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0028_alter_service_cost_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="service", name="consumables",),
        migrations.AlterField(
            model_name="service",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
