# Generated by Django 4.2.1 on 2023-07-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0029_remove_service_consumables_alter_service_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="discount",
            field=models.BooleanField(default=True),
        ),
    ]
