# Generated by Django 4.2.1 on 2023-07-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0030_service_discount"),
    ]

    operations = [
        migrations.AlterModelOptions(name="service", options={"ordering": ["type"]},),
        migrations.AlterField(
            model_name="cashboxoperation",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
