# Generated by Django 4.2.1 on 2023-07-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0032_orderconsumables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderconsumables",
            name="cost_price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderconsumables", name="count", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderconsumables", name="price", field=models.IntegerField(),
        ),
    ]
