# Generated by Django 4.2.1 on 2023-07-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0033_alter_orderconsumables_cost_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderconsumables",
            name="cost_price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderconsumables",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderconsumables",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
