# Generated by Django 4.2.1 on 2023-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0034_alter_orderconsumables_cost_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="single",
            field=models.BooleanField(default=False),
        ),
    ]
