# Generated by Django 4.2.1 on 2023-07-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0035_service_single"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="discount", field=models.IntegerField(default=0),
        ),
    ]
