# Generated by Django 4.2.1 on 2023-07-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crm_app",
            "0037_alter_orderservice_employer_alter_orderservice_order_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="acceptance",
            field=models.BooleanField(default=False),
        ),
    ]
