# Generated by Django 4.2.1 on 2023-07-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0040_alter_cashboxoperation_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="modelchangelog", name="change_type",),
    ]
