# Generated by Django 4.2.1 on 2023-07-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0041_remove_modelchangelog_change_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelchangelog",
            name="change_type",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
