# Generated by Django 4.2.1 on 2023-06-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("count", models.IntegerField(default=0)),
                ("declared_quantity", models.IntegerField(default=0)),
                ("actual_quantity", models.IntegerField(default=0)),
                ("size", models.CharField(max_length=30)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                ("composition", models.CharField(blank=True, max_length=150)),
                ("brand", models.CharField(blank=True, max_length=90)),
                ("defective", models.IntegerField(blank=True, null=True)),
                ("good_quality", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("ghest_circumference", models.IntegerField(blank=True)),
                ("girth_waist", models.IntegerField(blank=True)),
                ("length", models.IntegerField(blank=True)),
                ("width", models.IntegerField(blank=True)),
                ("height", models.IntegerField(blank=True)),
                ("comment", models.TextField(blank=True)),
                ("confirmation", models.BooleanField(default=False)),
            ],
        ),
    ]
