# Generated by Django 4.2.1 on 2023-06-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0002_employerproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
