# Generated by Django 4.2.1 on 2023-06-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0010_modelchangelog_new_value_modelchangelog_old_value_and_more"),
        ("crm_warehouse", "0003_alter_product_name_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm_app.order",
            ),
            preserve_default=False,
        ),
    ]
