# Generated by Django 4.2.1 on 2023-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0004_product_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
