# Generated by Django 4.2.1 on 2023-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crm_warehouse",
            "0007_alter_product_actual_quantity_alter_product_brand_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="on_warehouse",
            field=models.BooleanField(default=True),
        ),
    ]
