# Generated by Django 4.2.1 on 2023-06-20 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm_warehouse", "0008_product_on_warehouse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employer_products",
                to="crm_warehouse.product",
            ),
        ),
        migrations.AlterField(
            model_name="employerproduct",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employer_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
