# Generated by Django 4.2.1 on 2023-06-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0009_alter_employerproduct_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="size",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
