# Generated by Django 4.2.1 on 2023-06-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0010_alter_product_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="article",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="barcode",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
