# Generated by Django 4.2.1 on 2023-06-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0014_service_before_defective"),
        ("crm_warehouse", "0011_product_article_product_barcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="crm_app.order",
            ),
        ),
    ]
