# Generated by Django 4.2.1 on 2023-06-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0012_alter_product_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="on_warehouse",),
        migrations.AddField(
            model_name="product",
            name="in_work",
            field=models.BooleanField(default=False),
        ),
    ]
