# Generated by Django 4.2.1 on 2023-06-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0013_remove_product_on_warehouse_product_in_work"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="ghest_circumference",),
        migrations.RemoveField(model_name="product", name="girth_waist",),
        migrations.RemoveField(model_name="product", name="height",),
        migrations.RemoveField(model_name="product", name="length",),
        migrations.RemoveField(model_name="product", name="width",),
        migrations.AddField(
            model_name="product",
            name="defective_check",
            field=models.BooleanField(default=False),
        ),
    ]
