# Generated by Django 4.2.1 on 2023-06-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0018_orderservice_confirmed"),
        ("crm_warehouse", "0014_remove_product_ghest_circumference_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="employerproduct", name="product",),
        migrations.AddField(
            model_name="employerproduct",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employer_products",
                to="crm_app.order",
            ),
            preserve_default=False,
        ),
    ]
