# Generated by Django 4.2.1 on 2023-06-24 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0015_remove_employerproduct_product_employerproduct_order"),
    ]

    operations = [
        migrations.RemoveField(model_name="employerproduct", name="date",),
        migrations.CreateModel(
            name="ProductInEP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "ep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm_warehouse.employerproduct",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm_warehouse.product",
                    ),
                ),
            ],
        ),
    ]
