# Generated by Django 4.2.1 on 2023-06-24 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0017_alter_productinep_ep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinep",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emp",
                to="crm_warehouse.product",
            ),
        ),
    ]
