# Generated by Django 4.2.1 on 2023-06-28 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0019_consumables_service_consumables"),
        ("crm_warehouse", "0019_productinep_user_alter_employerproduct_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="SetOfServices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="crm_warehouse.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceInSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="crm_app.service",
                    ),
                ),
                (
                    "set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm_warehouse.setofservices",
                    ),
                ),
            ],
        ),
    ]
