# Generated by Django 4.2.1 on 2023-06-28 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_app", "0019_consumables_service_consumables"),
        ("crm_warehouse", "0020_setofservices_serviceinset"),
    ]

    operations = [
        migrations.RemoveField(model_name="setofservices", name="product",),
        migrations.AddField(
            model_name="setofservices",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm_app.order",
            ),
            preserve_default=False,
        ),
    ]
