# Generated by Django 4.2.1 on 2023-07-07 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm_warehouse", "0023_productinorder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinep",
            name="ep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_products",
                to="crm_warehouse.employerproduct",
            ),
        ),
        migrations.AlterField(
            model_name="productinep",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employer_products",
                to="crm_warehouse.product",
            ),
        ),
    ]
